export const FETCH_COUNTRIES = "FETCH_DATA";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_COUNTRIES_FAILURE = "FETCH_DATA_FAILURE";
export const FETCH_DETAILS = "FETCH_DETAILS";
export const FETCH_DETAILS_SUCCESS = "FETCH_DETAILS_SUCCESS";
export const FETCH_DETAILS_FAILURE = "FETCH_DETAILS_FAILURE";
